version:  '3.3'

services:
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - ../var/:/var/www/symfony/var
            - ../vendor/:/var/www/symfony/vendor
        ports:
            - 8082:80
        networks:
            app-network:
                aliases:
                    - rekrutacja.local
        env_file:
            - .env.nginx.local

    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - ../var/:/var/www/symfony/var
            - ../vendor/:/var/www/symfony/vendor
        networks:
            - app-network

    database:
        image: mariadb:10.4
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: my_database
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge

